services:
  - type: web
    name: chatapp-service
    env: docker
    plan: starter
    region: oregon  # You can change this to your preferred region
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 8080
      - key: TZ
        value: UTC
    healthCheckPath: /actuator/health
    autoDeploy: true
    buildCommand: ""  # Docker handles building
    startCommand: ""   # Docker handles starting
    scaling:
      minInstances: 1
      maxInstances: 3
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
