server:
  port: 8080

spring:
  application:
    name: chat-app-service
  
  # Security configuration
  security:
    user:
      name: admin
      password: admin123

# Anthropic API configuration
anthropic:
  api:
    key: ${ANTHROPIC_API_KEY:your-api-key-here}
    base-url: https://api.anthropic.com
    model: claude-3-sonnet-20240229
    max-tokens: 1000
    temperature: 0.7

# Logging configuration
logging:
  level:
    com.mychatbot: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
